### ISSUE TITLE
Invalid JSON 

### ISSUE THREAD

**Issue by LGuilhas** [bakdata/aws-lambda-r-runtime#12]
While exposing the lambda through API gateway in passthrough mode I found that the json payload was getting split on the commas thus failing in the conversion to a R object.

 In order to have the complete json pass as a string I had to adjust the bootstrap file to put the $EVENT_DATA between double quotes.

  /opt/R/bin/Rscript /opt/runtime.R “$EVENT_DATA” $REQUEST_ID.

**Comment by philipp94831** [comment]
Hi @LGuilhas,
thanks for spotting that. Do you want to submit a PR or shall I fix that myself?
Cheers

**Comment by LGuilhas** [comment]
Hi Phillip,

If you can please go ahead as you’re probably more comfortable with the project.

Cheers

No dia 22/03/2019, às 06:26, Philipp Schirmer <notifications@github.com<mailto:notifications@github.com>> escreveu:


Hi @LGuilhas<https://github.com/LGuilhas>,
thanks for spotting that. Do you want to submit a PR or shall I fix that myself?
Cheers

**Comment by philipp94831** [comment]
@LGuilhas I fixed the issue. I also added integration tests using sam local to prevent such errors in the future. Thanks for spotting that again!
