### ISSUE TITLE
API gateway curl request example

### ISSUE THREAD

**Issue by selcukakbas** [bakdata/aws-lambda-r-runtime#2]
I've deployed your example api on lambda, and opened api gateway. Test succeeded.
Can you give an example how can we make request with curl ?

what I tries so far

```
library(curl)
h <- new_handle()
handle_setform(h, payload = jsonlite::toJSON( data.frame(x = 1 ) ) )  
handle_setform(h, payload = jsonlite::toJSON(  list("x" = 1 ) ) )  # this also sisnt work
req <- curl_fetch_memory("https://myapigateway.execute-api.eu-central-1.amazonaws.com/default/r-example", handle = h)
jsonlite::prettify(rawToChar(req$content))
```

```
library(crul)
req <-  crul::HttpRequest$new(
  url = "https://myapigateway.execute-api.eu-central-1.amazonaws.com/default/r-example", 
  headers = list(`Content-Type` = "application/json")
)$post(payload = jsonlite::toJSON( list(x = 1 ) ) )

out <- AsyncVaried$new(req)
out$request()
out$parse() 
```

**Comment by philipp94831** [comment]
Hi @selcukakbas 
So you have a lambda which is able to run your R code and created an API gateway for this lambda?
Is the code you provide running inside your lambda or outside on your machine?

**Comment by selcukakbas** [comment]
Hi @philipp94831, I run this code on my machine

I was expecting to use api like this
https://myapigateway.execute-api.eu-central-1.amazonaws.com/default/r-example?x=1

**Comment by philipp94831** [comment]
Hi @selcukakbas 
what lambda function is deployed behind your API Gateway?
With our lambda layer you are able to run R on AWS Lambda. You can then connect this lambda with API Gateway to have a REST API, just as in this tutorial https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html
I do not know how you can then call your API from R on your machine. Maybe you should test it with curl from command line first to see if it works. Anyways, how you consume your REST API is independent from the lambda itself.

**Comment by selcukakbas** [comment]
thanks, 

this also does not work. I will find a way I hope. Will let you know.

curl -v -X POST \
'https://myapigateway.execute-api.eu-central-1.amazonaws.com/default/r-example' \
  -H 'content-type: application/json' \
  -H 'x-amz-docs-region: eu-central-1' \
  -d '{"x": 1}'

**Comment by philipp94831** [comment]
@selcukakbas 
Is your Lambda implemented in R? There are also test events with templates for API Gateway in the console which you can configure for Lambda. Furthermore the API Gateway console lets you test you endpoints and you can have a look at the logs in CloudWatch

**Comment by michael-mansour** [comment]
@selcukakbas Hi I have you find a solution ? I am also trying to call my R function with curl trough the API Gateway but without success.
Thanks

**Comment by philipp94831** [comment]
@michael-mansour there is a test for API gateway support in https://github.com/bakdata/aws-lambda-r-runtime/blob/master/tests/R/api.R. It can be deployed with this SAM template: https://github.com/bakdata/aws-lambda-r-runtime/blob/master/test-template.yaml

**Comment by michael-mansour** [comment]
@philipp94831 Thank you so much for your reply! Unfortunately I got the following error:
"Internal server error". And in the CloudWatch Logs I see the following error:

> ERROR:runtime:error: unused arguments

In fact I am new to AWS and I have followed the steps described in the exemple to run this very simple exemple:
https://github.com/bakdata/aws-lambda-r-runtime/blob/master/example/script.R

I am able to invoke the function trough AWS CLI using the command described in the read-me
```
aws lambda invoke --function-name r-matrix-example response.txt
cat response.txt
```
Now I want to invoke the same function trough https by passing the variable "x" like that:
/default/r-example?x=1

I have tried a lot of different way to archive that including the template that you have just mentioned without any results, I still got the same error.

Thank you so much for your help

**Comment by philipp94831** [comment]
@michael-mansour You need to use a function which takes arguments as in  [this example](https://github.com/bakdata/aws-lambda-r-runtime/blob/master/tests/R/api.R). The set of arguments passed by API Gateway is fixed and thus the signature of your function must look as in the example.

**Comment by michael-mansour** [comment]
@philipp94831  I have tried:
<img width="1532" alt="Screenshot 2019-08-25 at 16 40 16" src="https://user-images.githubusercontent.com/9451389/63651647-4843dd00-c757-11e9-8726-77ad4b7d1d0f.png">

but I got this error again and again 
<img width="1226" alt="Screenshot 2019-08-25 at 16 40 55" src="https://user-images.githubusercontent.com/9451389/63651651-5560cc00-c757-11e9-9afa-c198bde58f6a.png">

**Comment by philipp94831** [comment]
@michael-mansour The signature of your function is different than in the example. At least add ... to your signature to capture the remaining arguments

**Comment by michael-mansour** [comment]
thank you so much 🙏🏼
