### ISSUE TITLE
Error running matrix.R

### ISSUE THREAD

**Issue by jraj002** [bakdata/aws-lambda-r-runtime#20]
I followed the instructions in the README to run the matrix.R example. However, the lambda execution fails with the following error message:

```
[1] "Sourcing 'matrix.r'"
Error in file(filename, "r", encoding = encoding) : 
cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
cannot open file 'matrix.r': No such file or directory
Execution halted
```

**Comment by philipp94831** [comment]
Hi @jraj002,
the referenced version in the README was outdated. I updated the README and it should work now. Thanks for spotting this!

**Comment by jraj002** [comment]
Works now. This is very helpful. Thanks!
