### ISSUE TITLE
Minimum required AWS CLI for publishing a layer

### ISSUE THREAD

**Issue by dorkalev** [bakdata/aws-lambda-r-runtime#3]
great resource, kudos for compiling it!

notice that in the ec2, the aws cli needs upgrade from 1.11 to 1.16 for publish-layer-version to be available

did this to get there:
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

**Comment by philipp94831** [comment]
Hi,
thanks for spotting that! I actually only used the EC2 instance to build R. I always built the runtime on my machine which has a more recent version of AWS CLI. I will update the documentation accordingly to make it more clear and also list the required AWS CLI version.

**Comment by dorkalev** [comment]
cool, moreover - the micro is not enough, it gets a MemoryError on publish-layer-version. I had to create an instance with more memory to sort this out. 

thanks for creating this awesome layer!
