### ISSUE TITLE
AMI in remote_compile_and_deploy.sh is not public

### ISSUE THREAD

**Issue by ngfrey** [bakdata/aws-lambda-r-runtime#43]
The command:  

` instance_id=$(aws ec2 run-instances --image-id ami-657bd20a --count 1 --instance-type t2.medium \
    --instance-initiated-shutdown-behavior terminate --iam-instance-profile Name='"'${PROFILE}'"' \
    --user-data '#!/bin/bash`  

calls an AMI that either doesn't exist or isn't publicly available. What AMI would you recommend we use instead?

**Comment by philipp94831** [comment]
Hi @ngfrey,
the AMI is provided by Amazon and should be public. Maybe they changed something in their end. As explained  [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) maybe try `ami-0cfbf4f6db41068ac`. Hope this helps :)

**Comment by ngfrey** [comment]
@philipp94831 Thank you. Using [this](https://aws.amazon.com/marketplace/server/configuration?productId=f37c8255-1ff9-48bd-b5da-b5046f4fee68&ref_=psb_cfg_continue) page I was able to find an AMI for my region (Oregon). I'm going to try to build a Lambda layer out on EMR using this setup this weekend. Again, thank you. 
-NF
