### ISSUE TITLE
Create layer for AWS libraries

### ISSUE THREAD

**Issue by zhifaliu** [bakdata/aws-lambda-r-runtime#5]
I will suggest to add some more base packages for AWS service as R code can easily integrate those aws components: 
library(aws.sqs)
library(aws.signature)
library(aws.s3) # already saw there, that's great
library(aws.sns)
library(utils)
library(tools)

**Comment by philipp94831** [comment]
Hi,
I am actually not an expert in R and don't know which packages are the most popular. Therefore, I only included the set of recommended packages and aws.s3 because that seemed natural to me. I think there is still some space left in the base layer and I will maybe add some packages. Especially including the aws packages makes sense.
Nonetheless, you can compile your own layer to start using these packages now already. Just see the README for more information.

**Comment by zhifaliu** [comment]
Here is an easy modification to get those package working
in your build_r.sh , add the following line of code 
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.signature")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("jsonlite")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.sqs")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.iam")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.ec2metadata")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.ec2")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.s3")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.sns")'
./bin/Rscript -e 'chooseCRANmirror(graphics=FALSE, ind=34); install.packages("aws.stats")'

in your build_runtime.sh, modify the recommand line 
recommended=(aws.ec2 aws.iam aws.ec2metadata aws.s3 aws.sns aws.sqs aws.signature httr jsonlite tools utils htmltab parsedate  boot class cluster codetools foreign KernSmooth lattice MASS Matrix mgcv nlme nnet rpart spatial survival)

in your build_recommended.sh, modify the recommand line 

recommended=(aws.ec2 aws.iam aws.ec2metadata aws.s3 aws.sns aws.sqs aws.signature httr jsonlite tools utils htmltab parsedate  boot class cluster codetools foreign KernSmooth lattice MASS Matrix mgcv nlme nnet rpart spatial survival)

**Comment by philipp94831** [comment]
Hi @zhifaliu,
I created a layer containing [awspack](https://cran.r-project.org/web/packages/awspack/index.html). See the README or #10 for more Information :-)
