### ISSUE TITLE
Workspace cleared between invocations

### ISSUE THREAD

**Issue by johan13** [bakdata/aws-lambda-r-runtime#50]
Most AWS lambda runtimes keep global variables around between invocations. The R runtime seems to clear it with `rm(list = ls())` and then source the code again after each invocation. This means we cannot cache data between calls and cannot keep database connections open. Is there any reason why the R runtime was implemented this way?

**Comment by philipp94831** [comment]
We did that because different Lambdas using the same runtime could be launched in the same lambda container and we want to avoid side effects. Furthermore, this should also increase security because we want to avoid that objects from one invocation are shared with a different invocation

**Comment by johan13** [comment]
Thank you for the quick reply!
My understanding was that each lambda function gets its own container. I understand the security-argument, but it is a little inconsistent compared to the AWS-provided runtimes.

I will try building the layer with and without clearing the environment and see which one we end up using. Until #49 is resolved, I guess I cannot use the pre-built layer anyway.
