### ISSUE TITLE
aws.lambda integration?

### ISSUE THREAD

**Issue by jonthegeek** [bakdata/aws-lambda-r-runtime#58]
I'm resurrecting the {[aws.lambda](https://github.com/cloudyr/aws.lambda)} package, and, once it's alive, I plan to update it to make creation of R lambdas as easy as possible.

If it's ok with you, I'd like to integrate your provided layers directly into the package (well, their names), so that users can launch R lambdas without having to dig into things too far (I'm sorting out how easy I can make things for packages beyond what you've done, but I'd at least like to allow use of those packages).

Do you have any objections?

**Comment by philipp94831** [comment]
Hi @jonthegeek,
feel free to do so. I don't see any objections with regard to our MIT license

**Comment by jonthegeek** [comment]
Fantastic! I didn't think so, but wanted to check before diving in.
