### ISSUE TITLE
Creating layer

### ISSUE THREAD

**Issue by jburke-IWT** [bakdata/aws-lambda-r-runtime#6]
Hi Philip,

Do I have to run the build_recommended to get the layer? Or an I just zip R/library/<MY LIBRARY> and load it manually through AWS lambda layers? I tried running build_recommended and it's creating R/library but the folder is empty and it's not creating a zip.

**Comment by philipp94831** [comment]
Hi @jburke-IWT,
to build a custom layer, you just need to zip the libraries and place them under `R/library/` in your archive. If you run `build_recommended.sh`, it should build such an archive for you which is non-empty. However, you need to provide a compiled R distribution for that. Please see the README for information on how to create such a distribution.
Nevertheless, you do not need to build the layer yourself, you can always use our distribution:

Available AWS regions:

* ap-northeast-1
* ap-northeast-2
* ap-south-1
* ap-southeast-1
* ap-southeast-2
* ca-central-1
* eu-central-1
* eu-north-1
* eu-west-1
* eu-west-2
* eu-west-3
* sa-east-1
* us-east-1
* us-east-2
* us-west-1
* us-west-2

Available R versions:
* 3_5_1

ARN: `arn:aws:lambda:${region}:131329294410:layer:r-recommended-${version}:1`
