### ISSUE TITLE
Change file extension to fit better with generally accepting R styling

### ISSUE THREAD

**Issue by dgduncan** [bakdata/aws-lambda-r-runtime#7]
File extensions of R scripts are generally accepted to end with .R and not .r as per common style guides and best practices.

http://adv-r.had.co.nz/Style.html
https://google.github.io/styleguide/Rguide.xml

As is the case, the loading scripts should either exclusively look for .R or conditionally find either .R or .r

**Comment by philipp94831** [comment]
Hi @dgduncan,
thanks for this information, I will change it :)

**Comment by LGuilhas** [comment]
This shows as closed but while using the code for my lambda I saw that the runtime.R is still looking for a lower case file and had to adjust it.

`file_name <- paste0(HANDLER_split[1], ".R")`

**Comment by philipp94831** [comment]
@LGuilhas I fixed the issue. I also added integration tests using sam local to prevent such errors in the future. Thanks for spotting that again!
